[build]
  # Répertoire de base pour le build
  base = "client"
  
  # Commande de build
  command = "npm run build"
  
  # Répertoire de publication (où se trouvent les fichiers statiques après le build)
  publish = "build"

[build.environment]
  # Version de Node.js
  NODE_VERSION = "18"
  # Version de npm
  NPM_VERSION = "9"

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers pour les fichiers statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers pour les fichiers CSS et JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration pour les fonctions serverless (si nécessaire)
[functions]
  directory = "netlify/functions"

# Configuration pour les formulaires (si vous utilisez Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Variables d'environnement (à configurer dans le dashboard Netlify)
# Ces variables doivent être définies dans le dashboard Netlify
# [context.production.environment]
#   REACT_APP_API_URL = "https://votre-backend.herokuapp.com"
#   REACT_APP_ENVIRONMENT = "production"

# [context.deploy-preview.environment]
#   REACT_APP_API_URL = "https://votre-backend-staging.herokuapp.com"
#   REACT_APP_ENVIRONMENT = "staging"

# [context.branch-deploy.environment]
#   REACT_APP_API_URL = "https://votre-backend-dev.herokuapp.com"
#   REACT_APP_ENVIRONMENT = "development"
